databases:
  - name: churoom-db
    databaseName: churoom_prod
    plan: free

services:
  - type: web
    name: churoom
    env: ruby
    plan: free
    region: singapore
    buildCommand: |
      set -euxo pipefail
      ruby -v
      gem -v
      gem install bundler -v 2.6.9
      bundle -v
      bundle config unset path || true
      bundle check || bundle install --without development test --jobs 4 --retry 3
      RAILS_ENV=production bin/rails assets:precompile
      RAILS_ENV=production bin/rails db:prepare
    startCommand: bash -lc 'set -euxo pipefail; ruby -v; bundle -v; bundle exec puma -C config/puma.rb'
    preDeployCommand: bundle exec rails db:prepare
    healthCheckPath: /up
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: churoom-db
          property: connectionString
      - key: RAILS_LOG_TO_STDOUT
        value: "1"
      - key: RAILS_SERVE_STATIC_FILES
        value: "1"
      - key: RAILS_MAX_THREADS
        value: "5"
      - key: WEB_CONCURRENCY
        value: "2"
      - key: APP_HOST
        value: churoom.onrender.com
      # メールを使うなら（値はダッシュボードで設定）
      - key: SMTP_USER
        value: churoom.info@gmail.com
      - key: SMTP_PASS
        sync: false
      - key: CONTACT_TO
        value: churoom.info@gmail.com
      - key: CONTACT_FROM
        value: churoom.info@gmail.com
